[package]
name = "bevy-online-campus"
version = "0.1.0"
edition = "2021"
default-run = "bevy-online-campus"

[dependencies]
bevy = "0.14"
bevy_rapier3d = "0.27"
bevy_renet = "0.0.12"
renet = "0.0.16"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
